INSERT INTO USER (ID, USER_ID, PW, USER_NM, EMAIL, CREATE_DATE) VALUES ('1', 'aaa', 'pwaaa', '홍길동', 'aa@aa.com', CURRENT_TIMESTAMP());
INSERT INTO USER (ID, USER_ID, PW, USER_NM, EMAIL, CREATE_DATE) VALUES ('2', 'bbb', 'pwbbb', '임꺽정', 'bb@bb.com', CURRENT_TIMESTAMP());

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, COUNT_OF_ANSWER) VALUES ('1', '1', 'test1', 'test1 test1', CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, COUNT_OF_ANSWER) VALUES ('2', '2', 'test2', 'test2 test2', CURRENT_TIMESTAMP(), 0);